#!/usr/bin/env bash

# SPDX-License-Identifier: AGPL-3.0

#    -----------------------------------------------------
#    Copyright © 2024, 2025, 2026  Pellegrino Prevete
#
#    All rights reserved
#    -----------------------------------------------------
#
#    This program is free software: you can redistribute
#    it and/or modify it under the terms of the
#    GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of
#    the License, or (at your option) any later version.
#
#    This program is distributed in the hope that it
#    will be useful, but WITHOUT ANY WARRANTY;
#    without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#    See the GNU Affero General Public License for
#    more details.
#
#    You should have received a copy of the
#    GNU Affero General Public License
#    along with this program.
#    If not, see <https://www.gnu.org/licenses/>.

# I don't remember why
# I had this shebang
# so let's have it just in case
# until next test
#!/data/data/com.termux/files/usr/bin/env bash

_bin="$(
  dirname \
    "$(command \
         -v \
	 "env")")"
_lib="${_bin}/../lib"
_share="${_bin}/../share"
_crash_bash="${_lib}/libcrash-bash/crash-bash"
_sourced \
  "${_crash_bash}" \
  2>"/dev/null" || \
source \
  "${_crash_bash}"

_root_requirements() {
  _check_cmd \
    "aapt" \
    "aapt"
  _check_cmd \
    "grep"
  _check_cmd \
    "su" \
    "sudo"
  _check_cmd \
    "wc" \
    "coreutils"
}

# shellcheck disable=SC2034
_global_variables() {
  get_date=""
  target_app=""
  get_mode=""
  color=""
  quiet=""
}

_apk_path_get() {
  local \
    _package_name="${1}" \
    _cmd=() \
    _out \
    _no_permission=() \
    _no_permission_flag
  _no_permission_flag="false"
  _no_permission+=(
    "cmd: Failure calling service package:"
      "Failed transaction ("
  )
  _cmd+=(
    "/system/bin/pm"
      path
      "${_package_name}"
  )
  _out="$(
    "${_cmd[@]}" \
    2>&1 || \
    true)"
  _out_lines="$(
    echo \
      "${_out}" |
        wc \
          -l)"
  _msg=(
    "Lines in output: '${_out_lines[*]}'."
  )
  _msg_info \
    "${_msg[*]}"
  if [[ "${_out}" == "${_no_permission[*]}"* ]]; then
    _msg=(
      "No permission to read package"
      "path. Suggested to give permission"
      "to user to read packages with"
      "'sudo"
        "pm"
          "grant"
            "com.termux"
              "android.permission.PACKAGE_USAGE_STATS'."
    )
    _msg_warning \
      "${_msg[*]}" \
      0
    _no_permission_flag="true"
  fi
  if [[ "${_out}" == "" || \
        "${_no_permission_flag}" == "true"  ]]; then
    _out="$(
      su \
        -c \
          "${_cmd[*]}" || \
      true)"
  fi
  _apk_path="${_out#package:}"
}

_root_get(){
  local \
    _package_name="${1}" \
    _apk_path \
    _cmd=() \
    _pkg \
    _pkgs=() \
    _labels=() \
    _app_label \
    _app_label_line \
    _app_label_lines
  _apk_path_get \
    "${_package_name}"
  _msg=(
    "Got application APK path"
    "'${_apk_path}'."
  )
  _msg_info \
    "${_msg[*]}"
  _app_label_line="$(
    aapt \
      dump \
        badging \
        "${_apk_path}" |
      grep \
        -e \
          "^application: label='")"
  _app_label_lines="$(
    echo \
      "${_app_label_line}" |
      wc \
        -l)"
  if (( 1 < "${_app_label_lines}" )); then
    _msg=(
      "More than a label found."
    )
    _msg_error \
      "${_msg[*]}" \
      1
  fi
  _app_label_line="${_app_label_line%$'\n'}"
  _app_label="${_app_label_line#application: label=\'}"
  _app_label="${_app_label% icon=\'*}"
  _app_label="${_app_label%\'*}"
  _msg=(
    "Got label"
    "'${_app_label}'."
  )
  _msg_info \
    "${_msg[*]}"
  echo \
    "${_app_label}"
  # _pkgs=( $( \
  #   su \
  #     -c \
  #     "${_cmd[@]}")
  # )
  # for _pkg in "${_pkgs[@]}"; do
  #   _app="${_pkg#package:*}"
  #   if [[ "${_app}" == "${_target}" ]]; then
  #     echo \
  #       'true'
  #     return \
  #       0
  #   fi
  # done
  # echo \
  #   'false'
}

_get_mode_auto_detect(){
  local \
    _mode \
    _os
  _os="$(
    uname \
      -o)"
  _mode="root"
  if [[ "${_os}" == "Android" ]]; then
    _mode="root"
  fi
  _set_override \
    "get" \
    "mode" \
    "${_mode}"
}

_app_name() {
  local \
    _target="${1}" \
    _mode="${2}" \
    _cmd=() \
    _msg=() \
    _args=() \
    _pkg \
    _app \
    _apps=() 
  if [[ "${_mode}" == "root" ]]; then
    _args+=(
      "${_target}"
    )
  else
    _msg=(
      "Unknown retrieval"
      "mode '${_mode}'."
    )
    _msg_error \
      "${_msg[*]}" \
      1
  fi
  "_${_mode}_get" \
    "${_args[@]}"
}

_set_overrides() {
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  _set_override \
    "get" \
    "date" \
    "$(_get_date_human)"
  _get_mode_auto_detect
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "                 Get date:   ${get_date}"
  _msg_info "                 Get mode:   ${get_mode}"
  _msg_info "                      App:   ${target_app}"
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true

Retrieves an installed application label given its package name.

Usage:

  ${app_name}
    [options]
    <app>

  options:

     -m <mode>            How to get installed apps.
                          It can be 'root'
                          Default: ${get_mode}

     -h                   This message.

     -v                   Enable verbose output

ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${1}"
}

_globals
_global_variables
# shellcheck disable=SC2004
# shellcheck disable=SC2034
while \
  getopts \
    'm:cvh?' \
    arg; do
  case \
    "${arg}" in
    m)
      override_get_mode="${OPTARG}" ;;
    c)
      override_color="y" ;;
    v)
      override_quiet="n" ;;
    h|?)
      _set_overrides
      _usage \
        0 ;;
    *)
      _msg=(
        "Invalid argument '${arg}'."
      )
      _msg_error \
        "${_msg[*]}" \
        0 && \
      _set_overrides
      _usage \
        1 ;;
  esac
done
shift \
  $((
    OPTIND - 1 \
  ))
if (( $# < 1 )); then
  _usage \
    1
fi
target_app="${1}"
_set_overrides
app_opts=(
  "${target_app}"
  "${get_mode}"
)
_show_config
_app_name \
  "${app_opts[@]}"

# vim:set sw=2 sts=-1 et:
